language: php

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.cache/composer

matrix:
    include:
        - php: 7.2
        - php: 7.2
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.3
        - php: 7.4
        - php: 8.0snapshot
          env: COMPOSER_FLAGS='--ignore-platform-req=php'
        - php: nightly
          env: COMPOSER_FLAGS='--ignore-platform-req=php'
    fast_finish: true

before_script:
    - if [[ $TRAVIS_PHP_VERSION  = '7.2' ]]; then PHPUNIT_FLAGS="--coverage-clover clover"; else PHPUNIT_FLAGS=""; fi
    - if [[ $TRAVIS_PHP_VERSION != '7.2' ]]; then phpenv config-rm xdebug.ini; fi
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit $PHPUNIT_FLAGS
    - vendor/bin/phpcs

after_success:
    - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then php ocular.phar code-coverage:upload --format=php-clover clover; fi
